// User
export const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID';
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA';

// Cart
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const SHOW_CART_DROPDOWN = 'SHOW_CART_DROPDOWN';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DECREASE_FROM_CART = 'DECREASE_FROM_CART';

// Shop
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_FAIL = 'FETCH_COLLECTIONS_FAIL';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
