// User
export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START';
export const GOOGLE_SIGNIN_FAIL = 'GOOGLE_SIGNIN_FAIL';
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START';
export const EMAIL_SIGNIN_FAIL = 'EMAIL_SIGNIN_FAIL';
export const EMAIL_SIGNIN_SUCCESS = 'EMAIL_SIGNIN_SUCCESS';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';

// Cart
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const SHOW_CART_DROPDOWN = 'SHOW_CART_DROPDOWN';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DECREASE_FROM_CART = 'DECREASE_FROM_CART';

// Shop
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_FAIL = 'FETCH_COLLECTIONS_FAIL';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
